# .github/workflows/code_checks.yaml
name: Code_Checks

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        stability: [ prefer-lowest, prefer-stable ]
        symfony-version: ['5.4', '6.0']
        experimental: [false]
        include:
          - php: '8.1'
            stability: prefer-stable
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist --optimize-autoloader
          vendor/bin/simple-phpunit install

      - name: Execute tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: 'weak'
        run: vendor/bin/phpunit --verbose


  #cs:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: shivammathur/setup-php@v2
        #with:
          #php-version: 8.0
          #coverage: none # disable xdebug, pcov
      #- run: composer install --no-progress
      #- run: composer cscheck


  #phpstan:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: shivammathur/setup-php@v2
        #with:
          #php-version: 8.0
          #coverage: none # disable xdebug, pcov
      #- run: composer install --no-progress
      #- run: composer phpstan
